
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  server:
    port: 9090

okta:
  client:
    scope: ${OKTA_CLIENT_SCOPE}

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-79580021.okta.com/oauth2/ausa8khazhLhrqATr5d7
          jwk-set-uri: https://dev-79580021.okta.com/oauth2/ausa8khazhLhrqATr5d7/v1/keys
  datasource:
    hikari: ## default connection pool
      connectionTimeout: 20000
      maximumPoolSize: 5
    ## PostgreSQL
    url: jdbc:postgresql://${POSTGRES_URL:localhost}:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:passw0rd}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
#      show_sql: true
  mvc:
    servlet:
      path: /api/v1

logging:
  level:
    org:
      springframework: INFO